#!/bin/sh

bspc monitor eDP-1 -d I II III IV V #laptop screen

# second monitor
if [[ $(xrandr -q | grep "HDMI-1 connected") ]]; then
    ~/.scripts/init_screen.sh
fi

bspc config border_width         3
bspc config window_gap           10
bspc config normal_border_color  "#2c2c3d"
#bspc config focused_border_color "#76946a"
bspc config focused_border_color "#d8dee9"
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Spotify desktop='^5'


~/.config/bspwm/keymaps.sh &
~/.config/bspwm/autostart.sh &

