#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1 -d I II III IV V #laptop screen

# second monitor
if [[ $(xrandr -q | grep "HDMI-1 connected") ]]; then
    bspc monitor HDMI-1 -d VI VII VIII IX X
fi

bspc config border_width         0
bspc config window_gap           6
#bspc config normal_border_color  "#76946a"
#bspc config focused_border_color "#c8c093"
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Spotify desktop='^5'


~/.config/bspwm/autostart.sh
